# Generated by Django 4.0.10 on 2023-08-01 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stay_sharp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_knifes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('series', models.CharField(blank=True, max_length=30, null=True)),
                ('steel', models.CharField(blank=True, max_length=20, null=True)),
                ('carbon', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('CrMoV', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('angle', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('honing_add', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('low_quality', 'low_quality'), ('medium_quality', 'medium_quality'), ('high_quality', 'high_quality'), ('premium_quality', 'premium_quality')], default='low_quality', max_length=20)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Grinding_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KJ', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('GA', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('RW', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)])),
                ('C1', models.FloatField(default=50.0)),
                ('C2', models.FloatField(default=28.6)),
                ('USH', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Honing_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KJ', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('GA', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('honing_add', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('RW', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)])),
                ('FVB_S', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)])),
                ('C3_C4', models.FloatField(default=128.1)),
                ('C5_C6', models.FloatField(default=51.4)),
                ('FVB_H', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Account_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('series', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('steel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('carbon', models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('CrMoV', models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('length', models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('width', models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('grinding_angle', models.FloatField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('honing_add', models.FloatField(blank=True, default='', null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(default=stay_sharp.models.get_superuser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
