# Generated by Django 4.1 on 2022-09-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0019_alter_all_knifes_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="all_knifes", old_name="user", new_name="owner",
        ),
    ]
