# Generated by Django 4.1 on 2022-09-10 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stay_sharp", "0020_rename_user_all_knifes_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_knifes",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
