# Generated by Django 4.1 on 2022-09-10 11:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stay_sharp", "0021_alter_all_knifes_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_knifes",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(django.contrib.auth.models.User),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
