# Generated by Django 4.1 on 2022-09-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0025_all_knifes_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="all_knifes", old_name="owner", new_name="user",
        ),
    ]
