# Generated by Django 4.1 on 2022-09-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0027_account_table_user_alter_account_table_comments"),
    ]

    operations = [
        migrations.RemoveField(model_name="all_knifes", name="user",),
    ]
