# Generated by Django 4.0.10 on 2023-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField()),
                ('visitor_id', models.CharField(default='AnonymousUser', max_length=20)),
                ('visitor_name', models.CharField(default='AnonymousUser', max_length=20)),
                ('visitor_IP', models.GenericIPAddressField(default='unknown')),
                ('visitor_email', models.EmailField(default='unknown', max_length=254)),
                ('visitor_tz', models.CharField(default='', max_length=10)),
                ('choose_visits', models.BooleanField(default=False)),
                ('calculation_visits', models.BooleanField(default=False)),
                ('account_table_visits', models.BooleanField(default=False)),
            ],
        ),
    ]
